### ISSUE TITLE
Use Redux + Rematch for View and State management

### ISSUE THREAD

**Issue by acnebs** [TokelPlatform/tokel_app#30]
After moving away from the multiple renderer process plan, initial thinking was to use `react-router` for view management. However, since this app will never be web-based (we'd be using a `MemoryRouter`), and we will probably need a separate state management library anyway, the more sensible option is probably to just go ahead and use `redux` for this, as all devs currently working on the project are familiar with it.

[Rematch](https://github.com/rematch/rematch) is a convenience wrapper around `redux` that should make it easier to work with for our (relatively) simple use-case, so going with that.

**Comment by piggydoughnut** [comment]
@acnebs this is resolved right? if so, please close 🖖🏽

**Comment by acnebs** [comment]
Closed in #31
