### ISSUE TITLE
Faucet button within the Tokel coin wallet

### ISSUE THREAD

**Issue by NutellaLicka** [TokelPlatform/tokel_app#42]
I suggest we add an easy to find faucet option into the wallet (noting this will have to be done over nSPV).
It could be presented as a coloured button that the user clicks and it actions the faucet. Once the faucet has been activated, we could add a timer onto the button to let the user know when they can use the faucet again (potentially changing the colour of the button during this time).

We can fund the faucet and limit it to a couple of transactions a day per address. Otherwise people can go through the normal process of buying some Tokel and holding it in their wallet.

**Comment by piggydoughnut** [comment]
Just to add to the above, the faucet will allow users to make txs within the TOKEL network without ending up in the situation when they want to make a transaction but have to purchase TOKEL to do it and then they just get annoyed.

So basically we will allow users to make 1-2 txs per day for free. And then if they wanna make more they will have to buy TOKEL but if its just a one off case they don't need to worry.

**Comment by NutellaLicka** [comment]
We are no longer using faucetCC as it wasn't mechanised the way we wanted and would take CC developer time that we currently do not have.
