### ISSUE TITLE
Window buttons are missing

### ISSUE THREAD

**Issue by jorian** [TokelPlatform/tokel_app#47]
![image](https://user-images.githubusercontent.com/10341677/117403119-f978af80-af07-11eb-858c-b4ae137e7cc8.png)

There should be buttons to close, minimize and resize the window.

Linux Ubuntu 20.04

**Comment by NutellaLicka** [comment]
Same on the windows (10) version. I haven't gotten past the login screen though to see if it's different once you log in.
