### ISSUE TITLE
Check how libnspv handles the private key after the user logs in

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_app#93]
To make sure we are handling users's WIF securely lets double check what is libnspv doing with the WIF.

**Comment by acnebs** [comment]
I've checked and `libnspv` is storing the WIF in memory in cleartext for 777 seconds, so it doesn't seem like us doing the same decreases overall security by an appreciable amount.

If and when we want to store the WIF for user convenience, then it should obviously be encrypted. Until then though, someone being able to exfiltrate a WIF from program memory without also having a keylogger on the user's computer seems... unlikely.

**Comment by piggydoughnut** [comment]
awesome, lets keep as is for now then :) Thank you for checking it.
